CREATE TABLE Telefono (		
NUMERO INT NOT NULL, 
CEDULAC INT NOT NULL, 
PRIMARY KEY (NUMERO, CEDULAC),
FOREIGN KEY (CEDULAC) REFERENCES CLIENTE(CEDULA)
);

CREATE TABLE Cuenta (
NUMEROCTA INT NOT NULL,
TIPO VARCHAR(60),
);


CREATE TABLE CLIENTE (
CEDULA		INT  NOT NULL, 
NOMBRE		VARCHAR(30),
APELLIDO1   VARCHAR (30),
APELLIDO2	VARCHAR (30),
CORREO		VARCHAR (50),
DIRECCION	VARCHAR (100),
IDASP		NVARCHAR(128),
PRIMARY KEY (CEDULA),
FOREIGN KEY (IDASP) REFERENCES AspNetUsers(Id),
);


ALTER TABLE Cuenta
add Cedula INT REFERENCES CLIENTE(CEDULA)

ALTER TABLE Cuenta
PRIMARY KEY (NUMEROCTA)
